spring.application.name=attendance-app

# =========================
# H2 Database
# =========================
spring.datasource.url=jdbc:h2:mem:attendanceapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# H2 Console
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# Thymeleaf
# =========================
spring.thymeleaf.cache=false

# =========================
# MyBatis
# =========================
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=jp.co.attendance.attendance_app.entity

# =========================
# Logging
# =========================
logging.level.jp.co.attendance.attendance_app.mapper=debug
